Repository LeeChangHyeong/CoffeeDeliveryProject, pull requests merged in 2024-06, with the labels that each got.

#3 [2024/06/20] feat/get-all-user >> 회원가입, 로그인시 필요한 User entity 구현
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/entity/User.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/enums/UserRoleEnum.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/enums/UserStatusEnum.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/repository/CafeRepository.java
Labels: 🌟 feat

#8 [2024/06/20] feat/create-menu >> 카페 메뉴 등록 기능 구현
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/MenuController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/dto/MenuRequestDto.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/dto/MenuResponseDto.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/entity/Menu.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/repository/MenuRepository.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/MenuService.java
Labels: 🌟 feat

#12 [2024/06/20] feat/get-all-user >> status, role 데이터 enum에서 -> db table에 저장
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/AdminUserController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/dto/UserResponseDto.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/entity/User.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/entity/UserRole.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/entity/UserStatus.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/enums/UserRoleEnum.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/enums/UserStatusEnum.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/initalizer/DataInitializer.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/repository/UserRoleRepository.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/repository/UserStatusRepository.java
Labels: 🌟 feat, ♻️ refactor

#11 [2024/06/20] feat/create-cafe >> Cafe Entity 구현
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/CafeController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/entity/Cafe.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/repository/CafeRepository.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/CafeService.java
Labels: 🌟 feat

#14 [2024/06/20] feat/create-order >> 주문 작성 기능 구현
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/OrderController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/dto/OrderRequestDto.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/dto/OrderResponseDto.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/entity/Order.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/entity/OrderStatus.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/repository/OrderRepository.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/OrderService.java
Labels: 🌟 feat, ♻️ refactor

#17 [2024/06/20] feat/update-orderstatus >> 주문 상태 변경 기능 구현
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/OrderController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/dto/MessageResponseDto.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/entity/Order.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/OrderService.java
Labels: 🌟 feat

#18 [2024/06/20] feat/delete-menu >> 카페 메뉴 삭제 기능 구현
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/MenuController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/dto/MessageResponseDto.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/MenuService.java
Labels: 🌟 feat, ♻️ refactor

#20 [2024/06/20] feat/get-all-user >> User의 Role, Status 타입과 관계 재설정 + 초기 User데이터 생성해주는 클래스 구현
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/CoffeeDeliveryProjectApplication.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/dto/UserResponseDto.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/entity/User.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/entity/UserRole.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/entity/UserStatus.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/enums/UserStatusEnum.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/initalizer/DataInitializer.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/repository/UserRepository.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/repository/UserRoleRepository.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/repository/UserStatusRepository.java
Labels: 🌟 feat, ♻️ refactor

#21 [2024/06/21] refactor/adminorder >> Admin 기능 분리
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/AdminOrderController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/OrderController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/dto/OrderResponseDto.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/entity/Order.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/entity/OrderStatus.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/AdminOrderService.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/OrderService.java
Labels: 🙋🏻‍♂️ question, ♻️ refactor

#23 [2024/06/21] feat/get-all-user >> 전체 회원 조회기능
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/AdminUserController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/AdminUserService.java
Labels: 🌟 feat

#25 [2024/06/21] feat/create-cafe >> 카페 페이지 작성 기능 구현
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/AdminCafeController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/CafeController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/dto/CafeRequestDto.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/dto/CafeResponseDto.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/entity/Cafe.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/AdminCafeService.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/CafeService.java
Labels: 🌟 feat, ♻️ refactor

#26 [2024/06/21] feat/create-menu >> Menu Entity Cafe Entity와 연관관계 맵핑
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/dto/MenuResponseDto.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/entity/Menu.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/MenuService.java
Labels: 🌟 feat, ♻️ refactor

#28 [2024/06/21] feat/delete-order >> 주문 삭제 기능 구현
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/AdminOrderController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/AdminOrderService.java
Labels: 🌟 feat

#31 [2024/06/21] feat/edit-user >> 유저 정보 수정 기능
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/AdminUserController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/dto/UserEditRequestDto.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/entity/User.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/exceptions/PasswordMismatchException.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/exceptions/RecentlyUsedPasswordException.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/exceptions/UserNotFoundException.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/initalizer/DataInitializer.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/AdminUserService.java
Labels: 🌟 feat

#33 [2024/06/21] feat/delete-user >> 특정 회원 삭제 기능
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/AdminUserController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/AdminUserService.java
Labels: 🌟 feat, ♻️ refactor

#35 [2024/06/21] feat/get-all-cafe >> 카페 페이지 전체 조회 기능 구현
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/AdminCafeController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/dto/CafeMenusResponseDto.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/entity/Cafe.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/AdminCafeService.java
Labels: 🌟 feat, ♻️ refactor

#39 [2024/06/21] feat/change-user-role >> 유저 권한 관리자로 변경
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/AdminUserController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/AdminUserService.java
Labels: 🌟 feat

#38 [2024/06/21] feat/signup >> 회원가입 기능 구현
  CoffeeDeliveryProject/build.gradle
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/UserController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/dto/SignupRequestDto.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/entity/User.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/jwt/JwtUtil.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/repository/UserRepository.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/security/UserDetailsImpl.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/security/UserDetailsServiceImpl.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/UserService.java
Labels: 🌟 feat

#42 [2024/06/22] feat/edit-cafe >> 카페 페이지 수정 기능 구현
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/AdminCafeController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/dto/CafeEditRequestDto.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/dto/CafeMenusResponseDto.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/entity/Cafe.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/AdminCafeService.java
Labels: 🌟 feat, ♻️ refactor

#41 [2024/06/21] feat/block-user >> 특정 유저 block하는 기능
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/AdminUserController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/entity/User.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/AdminUserService.java
Labels: 🌟 feat

#46 [2024/06/22] feat/delete-cafe >> 카페 페이지 삭제 기능 구현
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/AdminCafeController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/AdminCafeService.java
Labels: 🌟 feat

#45 [2024/06/22] feat/edit-profile >> 유저 본인 프로필 수정 기능
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/AdminUserController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/UserController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/dto/UserProfileEditRequestDto.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/dto/UserProfileEditResponseDto.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/UserService.java
Labels: 🌟 feat

#49 [2024/06/22] Feat/signup >> 회원가입 기능
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/config/PasswordConfig.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/UserController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/UserService.java
Labels: 🌟 feat, ♻️ refactor

#48 [2024/06/22] feat/logout >> 로그아웃 기능 구현
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/UserController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/entity/User.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/UserService.java
Labels: 🌟 feat

#51 [2024/06/22] feat/get-all-cafe-user >> 일반 유저 카페 페이지 전체 조회 기능 구현
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/CafeController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/CafeService.java
Labels: 🌟 feat

#53 [2024/06/22] feat/get-cafe-user >> 일반 유저 카페 페이지 단건 조회 기능 구현
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/AdminMenuController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/CafeController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/dto/CafeMenuListResponseDto.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/entity/Cafe.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/AdminMenuService.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/CafeService.java
Labels: 🌟 feat, ♻️ refactor

#57 [2024/06/23] refactor/valid-cafe >> Cafe API 관련 Validation과 예외처리
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/AdminCafeController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/dto/CafeRequestDto.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/repository/CafeRepository.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/AdminCafeService.java
Labels: 🌟 feat, ♻️ refactor

#60 [2024/06/23] refactor/valid-menu >> menu API 관련 Validation
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/AdminMenuController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/dto/MenuRequestDto.java
Labels: ♻️ refactor

#58 [2024/06/23] feat/get-review >> 리뷰 작성, 수정, 조회 삭제 기능
  .idea/.gitignore
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/delivery.iml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/ReviewController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/dto/ReviewRequestDto.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/dto/ReviewResponseDto.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/entity/Review.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/repository/ReviewRepository.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/ReviewService.java
Labels: 🌟 feat

#61 [2024/06/24] Feat/login >> 로그인 기능 구현
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/UserController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/dto/LogingRequestDto.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/jwt/JwtUtil.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/UserService.java
Labels: 🌟 feat, 🩹 fix

#65 [2024/06/24] feat/exception-handler >> ExceptionHandler 기능 구현
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/AdminUserController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/exceptions/GlobalExceptionHandler.java
Labels: 🌟 feat

#66 [2024/06/24] feat/login >> 회원가입 시 role 값 USER, ADMIN 들어오게 수정
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/dto/SignupRequestDto.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/entity/User.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/UserService.java
Labels: 🌟 feat

#68 [2024/06/24] feat/SecurityConfig >> 시큐리티 config 및 인가 필터 구현
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/config/WebSecurityConfig.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/CafeLikeController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/OrderController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/ReviewLikeController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/entity/CafeLike.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/entity/Order.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/entity/Review.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/entity/ReviewLike.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/repository/CafeLikeRepository.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/repository/OrderRepository.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/repository/ReviewLikeRepository.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/security/JwtAuthorizationFilter.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/CafeLikeService.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/OrderService.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/ReviewLikeService.java
Labels: 🌟 feat

#70 [2024/06/24] feat/authorization-order >> 주문상태 관련 API 어드민만 가능하도록 변경
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/AdminOrderController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/AdminOrderService.java
Labels: 🌟 feat, ♻️ refactor

#71 [2024/06/24] feat/reissue-token >> 만료된 액세스 토큰 재발급 기능 구현
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/UserController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/dto/SignupRequestDto.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/jwt/JwtUtil.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/security/JwtAuthorizationFilter.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/UserService.java
Labels: 🌟 feat, ♻️ refactor

#73 [2024/06/24] feat/authorization-user >> 관리자 권한 부분 인증 후 사용
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/AdminUserController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/dto/SignupRequestDto.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/AdminUserService.java
Labels: 👾 bug, 🌟 feat, 🩹 fix

#75 [2024/06/24] refactor/admin-cafe >> Cafe, Menu API Admin 확인 기능 구현
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/config/WebSecurityConfig.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/AdminCafeController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/AdminMenuController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/CafeController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/AdminCafeService.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/AdminMenuService.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/CafeService.java
Labels: 🌟 feat, ♻️ refactor, 🩹 fix

#76 [2024/06/24]feat/authorization-review >> Review 본인 확인 기능 구현
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/ReviewController.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/entity/Review.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/repository/ReviewRepository.java
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/ReviewService.java
Labels: 🌟 feat

#77 [2024/06/24] feat/unlike-reivew >> 리뷰 좋아요 취소기능
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/controller/ReviewLikeController.java
Labels: 🌟 feat

#78 [2024/06/24] feat/get-order >> 주문 목록이 비어있을 때 오류 처리
  CoffeeDeliveryProject/src/main/java/com/sparta/coffeedeliveryproject/service/OrderService.java
Labels: ♻️ refactor
